# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dlib Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dlib Project
  pod 'Objection', '~> 1.6.1'

  target 'Dlib ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
