# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Object Detector' do
	pod 'OpenCV', '2.4.9'
end

target 'Object DetectorTests' do

end

